apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2022-03-27T14:59:28Z"
  labels:
    kubernetes.io/metadata.name: sample
  name: sample
  uid: 5749d682-d0da-4022-b599-d2258fcd3934
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
